// List of portfolio pages with name, url, and status. Only pages with 'active' status will appear. Use 'inactive' to hide websites that are down or perhaps no longer maintained.
const sites = [
  {'name': 'Aaron Koelker', 'url': 'https://aaronkoelker.com/', 'status': 'active'},
  {'name': 'Aaron Taveras', 'url': 'https://www.cartografix.co/', 'status': 'active'},
  {'name': 'Adam Wilbert', 'url': 'https://cartogaia.com/', 'status': 'active'},
  {'name': 'Adina Renner', 'url': 'https://www.adinarenner.com/', 'status': 'active'},
  {'name': 'Adrián Blanco Ramos', 'url': 'https://adrianblancoramos.com/#projects', 'status': 'active'},
  {'name': 'Alan McConchie', 'url': 'https://mappingmashups.net/#portfolio', 'status': 'active'},
  {'name': 'Alex Fries', 'url': 'https://acfries.github.io/', 'status': 'active'},
  {'name': 'Alex Hotchin', 'url': 'https://alexhotchin.com/', 'status': 'active'},
  {'name': 'Alex McPhee', 'url': 'https://pronghornmaps.com/', 'status': 'active'},
  {'name': 'Aly Ollivierre', 'url': 'https://www.alyollivierre.com/', 'status': 'active'},
  {'name': 'Amparo Guindón', 'url': 'https://www.amparoguindon.com/', 'status': 'active'},
  {'name': 'Andrew Douglas-Clifford', 'url': 'https://www.andrewdc.co.nz/', 'status': 'active'},
  {'name': 'Andrew Duggan', 'url': 'https://andrewmaps.com/product-category/cartograms/', 'status': 'active'},
  {'name': 'Andrew Lynch', 'url': 'https://vanmaps.com/portfolio/', 'status': 'active'},
  {'name': 'Andrew Tyrrell', 'url': 'https://southarrowmaps.co.nz/', 'status': 'active'},
  {'name': 'Andria Olson', 'url': 'http://www.andriaolson.com/', 'status': 'inactive'},
  {'name': 'Andy Woodruff', 'url': 'https://andywoodruff.com/', 'status': 'active'},
  {'name': 'Angeline Meeks', 'url': 'https://www.angelinemaps.com/', 'status': 'active'},
  {'name': 'Anna Eshelman', 'url': 'https://www.annaeshelman.com/maps', 'status': 'active'},
  {'name': 'Anna Riling', 'url': 'https://www.fourcornersmapping.com/', 'status': 'active'},
  {'name': 'Anton Thomas', 'url': 'https://www.antonthomasart.com/', 'status': 'active'},
  {'name': 'Atlas Guo', 'url': 'https://cartoguophy.com/portfolio.html', 'status': 'active'},
  {'name': 'Aurélien Boyer-Moraes', 'url': 'https://transit-map.com/', 'status': 'active'},
  {'name': 'Austin Beck', 'url': 'https://austinbeck-geo.com/', 'status': 'inactive'},
  {'name': 'Ayeisha Sheldon', 'url': 'https://www.ayeishasheldon.com/cartography', 'status': 'active'},
  {'name': 'Bad Hoss Maps', 'url': 'https://www.badhossmaps.com/shop', 'status': 'active'},
  {'name': 'Bella Mironova', 'url': 'https://bella-mir.com/#/projects', 'status': 'active'},
  {'name': 'Bob Johnson', 'url': 'https://vinethos.com/bob-johnson-vineyard-maps/', 'status': 'active'},
  {'name': 'Camila Narbaitz Sarsur', 'url': 'https://www.cnscartography.com/my-work.html', 'status': 'active'},
  {'name': 'Capucine Defretin', 'url': 'https://www.capucine-illustrationsarchitecture.fr/', 'status': 'active'},
  {'name': 'Carl Churchill', 'url': 'http://www.churchillgeo.com/', 'status': 'active'},
  {'name': 'Carlos Arrojo', 'url': 'https://www.carlosarrojo.com/', 'status': 'active'},
  {'name': 'Catherine Wang', 'url': 'http://catherinewang.ca/', 'status': 'active'},
  {'name': 'Cathy Fussell', 'url': 'https://www.cathyfussellquilts.com/#/map-quilts/', 'status': 'active'},
  {'name': 'Chaney Swiney', 'url': 'http://chaneyswiney.com/cartography', 'status': 'active'},
  {'name': 'Chiara Phillips', 'url': 'https://www.chiaraphillips.com/', 'status': 'active'},
  {'name': 'Chloe the Cartographer', 'url': 'https://chloethecartographer.com/portfolio/', 'status': 'active'},
  {'name': 'Chris Brackley', 'url': 'https://www.atcfc.ca/map-gallery.html', 'status': 'active'},
  {'name': 'Christina Shintani', 'url': 'https://www.shintanimaps.com/', 'status': 'active'},
  {'name': 'Claire Fanjul', 'url': 'https://clairefanjul.fr/oeuvres/sphere.html', 'status': 'active'},
  {'name': 'Clara Bowe', 'url': 'https://clarakmbowe.com/crewel-and-kind/', 'status': 'active'},
  {'name': 'Coco Menk', 'url': 'https://cocomenk.net/gis', 'status': 'active'},
  {'name': 'Cooper Thomas', 'url': 'http://cooper-thomas.com/', 'status': 'active'},
  {'name': 'Courtney Simonse', 'url': 'https://courtneysimonse.ninja/', 'status': 'active'},
  {'name': 'Craig Taylor', 'url': 'https://mapzilla.co.uk/', 'status': 'active'},
  {'name': 'Damien Saunder', 'url': 'https://www.damiensaunder.com/', 'status': 'active'},
  {'name': 'Dan Bowles', 'url': 'https://www.behance.net/danbowles', 'status': 'active'},
  {'name': 'Danai-Maria Kontou', 'url': 'https://danaiscosmographics.com/work/maps', 'status': 'active'},
  {'name': 'Daniel Coe', 'url': 'https://dancoecarto.com/work', 'status': 'active'},
  {'name': 'Daniel Huffman', 'url': 'https://somethingaboutmaps.com/Client-Work', 'status': 'active'},
  {'name': 'Danielle Currie', 'url': 'https://www.satellitestitches.com/', 'status': 'active'},
  {'name': 'Darren Sears', 'url': 'https://www.darrensears.com/', 'status': 'active'},
  {'name': 'David A. Garcia', 'url': 'https://www.davidgarciastudio.com/map', 'status': 'active'},
  {'name': 'David Garcia', 'url': 'https://www.mapmakerdavid.com/', 'status': 'inactive'},
  {'name': 'David Imus', 'url': 'https://imusgeographics.com/', 'status': 'active'},
  {'name': 'David Kulbeth', 'url': 'https://www.columbuscartography.com/maps', 'status': 'active'},
  {'name': 'Derek Watkins', 'url': 'https://dwtkns.com/', 'status': 'active'},
  {'name': 'Diana Bonnarens', 'url': 'https://www.gistdoinmybest.com/cartography', 'status': 'active'},
  {'name': 'Diane Berg', 'url': 'https://diane-berg.com/projets/', 'status': 'active'},
  {'name': 'Dilara Bozkurt', 'url': 'https://www.dilarabozkurt.com/projects', 'status': 'active'},
  {'name': 'Doug John Miller', 'url': 'https://www.dougjohnmiller.com/', 'status': 'active'},
  {'name': 'Dylan Moriarty', 'url': 'https://moriartymaps.com/', 'status': 'active'},
  {'name': 'Eduardo Asta', 'url': 'https://www.behance.net/eduardoasta', 'status': 'active'},
  {'name': 'Eleanor Lutz', 'url': 'https://eleanorlutz.com/work', 'status': 'active'},
  {'name': 'Elliott Park', 'url': 'https://columbiapressworks.com/collections', 'status': 'active'},
  {'name': 'Eric Knight', 'url': 'https://www.ericknightmaps.com/panoramas', 'status': 'active'},
  {'name': 'Erick Ingraham', 'url': 'https://www.erickingraham.com/maps', 'status': 'active'},
  {'name': 'Erin Davis', 'url': 'https://erdavis.com/', 'status': 'active'},
  {'name': 'Erin Greb', 'url': 'https://eringrebcartography.com/', 'status': 'active'},
  {'name': 'Eva Massi', 'url': 'https://www.evamassi.com/cartography', 'status': 'active'},
  {'name': 'Evan Applegate', 'url': 'https://evanapplegate.com/', 'status': 'active'},
  {'name': 'Federica Fragapane', 'url': 'https://www.behance.net/FedericaFragapane', 'status': 'active'},
  {'name': 'Francesca Baerald', 'url': 'http://www.francescabaerald.com/worldmaps/', 'status': 'active'},
  {'name': 'Gabriel Camus', 'url': 'https://www.instagram.com/gabrielcamus.art/', 'status': 'active'},
  {'name': 'Gernot Nikolaus', 'url': 'https://gernotnikolaus.github.io/gallery', 'status': 'active'},
  {'name': 'Ginny Mason', 'url': 'https://ginnymason.com/', 'status': 'active'},
  {'name': 'Grant Preller', 'url': 'https://www.instagram.com/bomboramaps/', 'status': 'active'},
  {'name': 'Gregor Turk', 'url': 'https://gregorturk.com/', 'status': 'active'},
  {'name': 'Guy Hastings', 'url': 'https://www.guyssurfarimaps.com/', 'status': 'active'},
  {'name': 'Hannah Dormido', 'url': 'https://hannahdormido.com/work/', 'status': 'active'},
  {'name': 'Harrison Cole', 'url': 'https://www.harrisoncarto.com/', 'status': 'active'},
  {'name': 'Heather Gabriel Smith', 'url': 'https://www.heathergabrielsmith.ca/art', 'status': 'active'},
  {'name': 'Helen Asimina Tosteson', 'url': 'https://helenasimina.github.io/hat-portfolio-cart/index.html', 'status': 'active'},
  {'name': 'Helen Cann', 'url': 'https://helencann.co.uk/', 'status': 'active'},
  {'name': 'Ilya Birman', 'url': 'https://ilyabirman.net/design/', 'status': 'active'},
  {'name': 'Isaac Dushku', 'url': 'https://lordofmaps.com/', 'status': 'active'},
  {'name': 'J. Maizlish Mole', 'url': 'https://www.jmaizlish.com/', 'status': 'active'},
  {'name': 'Jake Coolidge', 'url': 'https://jakecoolidgecartography.com/#', 'status': 'active'},
  {'name': 'Jan Paul Miene', 'url': 'https://jpmiene.wordpress.com/projects/', 'status': 'active'},
  {'name': 'Jakob Listabarth', 'url': 'https://jakoblistabarth.com/', 'status': 'active'},
  {'name': 'James Cheshire', 'url': 'https://jcheshire.com/', 'status': 'active'},
  {'name': 'James Cheshire', 'url': 'https://jcheshire.com/', 'status': 'active'},
  {'name': 'Jamshid Kooros', 'url': 'http://www.koorosmaps.com/welcome.html', 'status': 'inactive'},
  {'name': 'Jan Kallwejt', 'url': 'https://kallwejt.com/', 'status': 'active'},
  {'name': 'Jane Crosen', 'url': 'https://www.mainemapmaker.com/index.html', 'status': 'active'},
  {'name': 'Jazzberry Blue', 'url': 'https://www.etsy.com/shop/JazzberryBlue?section_id=14208496', 'status': 'active'},
  {'name': 'Jean-Louis Rheault', 'url': 'http://jlrmaps.com/portfolio.html', 'status': 'active'},
  {'name': 'Jeff Clark', 'url': 'https://www.clarkgeomatics.ca/', 'status': 'active'},
  {'name': 'Jeff Murray', 'url': 'https://www.jeffmurray.co.uk/', 'status': 'active'},
  {'name': 'Jeffrey Linn', 'url': 'https://conspiracyofcartographers.com/', 'status': 'active'},
  {'name': 'Jessica Gosling-Goldsmith', 'url': 'https://www.gosling-goldsmith.com/maps', 'status': 'active'},
  {'name': 'Jessie Friend', 'url': 'https://afriendon.earth/', 'status': 'active'},
  {'name': 'Jen Urso', 'url': 'https://steadyhandmaps.com/map-showcase/', 'status': 'active'},
  {'name': 'Jenni Sparks', 'url': 'https://jennisparks.com/', 'status': 'active'},
  {'name': 'Jenny Janssen', 'url': 'https://www.behance.net/jennyjanssen', 'status': 'active'},
  {'name': 'Jeremy Collins', 'url': 'https://jercollins.com/all-products', 'status': 'active'},
  {'name': 'Jess Baker', 'url': 'https://www.jessbakermapping.com/my-work', 'status': 'active'},
  {'name': 'John Nelson', 'url': 'https://adventuresinmapping.com/', 'status': 'active'},
  {'name': 'Joshua Stevens', 'url': 'https://www.joshuastevens.net/portfolio/', 'status': 'active'},
  {'name': 'Josie Sajbel', 'url': 'https://sajbelcart.github.io/', 'status': 'active'},
  {'name': 'Juan Francisco Saldarriaga', 'url': 'https://juanfrans.com/', 'status': 'active'},
  {'name': 'Jug Cerovic', 'url': 'https://www.jugcerovic.com/', 'status': 'active'},
  {'name': 'Jules Grandin', 'url': 'http://julesgrandin.com', 'status': 'active'},
  {'name': 'Julian Hoffmann Anton', 'url': 'https://www.julian-hoffmann-anton.com/networks-and-maps', 'status': 'active'},
  {'name': 'Juliette Bricker', 'url': 'https://juliettebricker.ca/', 'status': 'active'},
  {'name': 'Karl van Es', 'url': 'https://avontuura.com/', 'status': 'active'},
  {'name': 'Kate Berg', 'url': 'https://www.pokateomaps.com/portfolio', 'status': 'active'},
  {'name': 'Kate Chidley', 'url': 'https://katechidley.com/product-category/maps/', 'status': 'active'},
  {'name': 'Kate Tarling', 'url': 'https://www.katetarlingtextiles.com/images', 'status': 'active'},
  {'name': 'Katie Armstrong', 'url': 'https://www.katie-armstrong.com/', 'status': 'active'},
  {'name': 'Kelby Beyer', 'url': 'https://kelbykbeyer.wixsite.com/kelbybeyer', 'status': 'active'},
  {'name': 'Kelsey Taylor', 'url': 'https://www.kelseyetaylor.com/portfolio', 'status': 'active'},
  {'name': 'Kenneth Field', 'url': 'https://cartoblography.com/', 'status': 'inactive'},
  {'name': 'Kevin Sheehan', 'url': 'https://www.manuscriptmaps.com/products', 'status': 'active'},
  {'name': 'Kirby Salvador', 'url': 'http://www.kirbysalvador.com/', 'status': 'active'},
  {'name': 'Kirsten Sparenborg', 'url': 'https://turnofthecenturies.com/', 'status': 'active'},
  {'name': 'Lana Bragin', 'url': 'https://www.ulani.de/', 'status': 'active'},
  {'name': 'Lara Lou', 'url': 'https://www.laura-lou.com', 'status': 'active'},
  {'name': 'Lauren C. Tierney', 'url': 'https://laurenctierney.com/', 'status': 'active'},
  {'name': 'Lee France', 'url': 'https://leefrance.me/', 'status': 'active'},
  {'name': 'Lewis Brownlie', 'url': 'https://lewisbrownlie.com/', 'status': 'active'},
  {'name': 'Lionel Portier', 'url': 'https://lionelportier.com/portfolio/maps-2/', 'status': 'active'},
  {'name': 'Loïc Brisout', 'url': 'https://www.sketchthestreets.com/', 'status': 'active'},
  {'name': 'Maddy Grubb', 'url': 'https://maddygrubbmaps.com/Portfolio.html', 'status': 'active'},
  {'name': 'Map Guy', 'url': 'https://themapguy.net/', 'status': 'active'},
  {'name': 'Marco Hernandez', 'url': 'https://mhinfographics.github.io/maps', 'status': 'active'},
  {'name': 'Margot Dale Carpenter', 'url': 'http://www.hartdalemaps.com/', 'status': 'active'},
  {'name': 'Marion Laplane', 'url': 'https://ml-illustrations.com/portfolio/', 'status': 'active'},
  {'name': 'Martin Elmer', 'url': 'https://maphugger.com/', 'status': 'inactive'},
  {'name': 'Matthew Dean Shaffer', 'url': 'https://www.matthewdeanshaffer.com/maps', 'status': 'active'},
  {'name': 'Mediaeval Mapmaker', 'url': 'https://www.etsy.com/shop/MediaevalMapmaker', 'status': 'active'},
  {'name': 'Mengyu Liang', 'url': 'https://mliang8.github.io/portfolio.html', 'status': 'active'},
  {'name': 'Michael Horner', 'url': 'https://www.cartisticendeavors.com/gallery', 'status': 'active'},
  {'name': 'Michael Karpovage', 'url': 'https://www.karpovagecreative.com/', 'status': 'active'},
  {'name': 'Michael Reagan', 'url': 'https://www.mreaganstudio.com/services-5', 'status': 'active'},
  {'name': 'Michelle Snyder', 'url': 'https://www.quaillanepress.com/', 'status': 'active'},
  {'name': 'Micmap', 'url': 'https://www.micmap.fr/en/works/', 'status': 'active'},
  {'name': 'Mike Hall', 'url': 'https://www.thisismikehall.com/', 'status': 'active'},
  {'name': 'Milan Vasek', 'url': 'https://www.milanvasek.com/', 'status': 'active'},
  {'name': 'Milana Glebova', 'url': 'https://www.behance.net/m_glebova', 'status': 'active'},
  {'name': 'Misti Wudtke', 'url': 'https://portfolio-alder.hub.arcgis.com/', 'status': 'active'},
  {'name': 'Molly Elkins', 'url': 'https://mollyelkins.weebly.com/portfolio.html', 'status': 'active'},
  {'name': "Molly O'Halloran", 'url': 'https://www.mollyohalloran.com/new-page', 'status': 'active'},
  {'name': 'Monica Hersher', 'url': 'https://www.monicahersher.com/', 'status': 'active'},
  {'name': 'Nadieh Bremer', 'url': 'https://www.visualcinnamon.com/portfolio/', 'status': 'active'},
  {'name': 'Naomi Rosenberg', 'url': 'https://naomirosenberg.com/accessible-media/', 'status': 'active'},
  {'name': 'Nat Case', 'url': 'https://www.incasellc.com/cartography-publication-design/', 'status': 'active'},
  {'name': 'Nate Padavick', 'url': 'https://www.natepadavick.com/illustrated-map-maker', 'status': 'active'},
  {'name': 'Nate Wessel', 'url': 'https://natewessel.com/cartography/', 'status': 'active'},
  {'name': 'Neil Gower', 'url': 'https://www.neilgower.com/Le-Manoir-Garden-Art', 'status': 'active'},
  {'name': 'Nelson Schäfer', 'url': 'https://nellomaps.com/', 'status': 'active'},
  {'name': 'Nich Bauch', 'url': 'https://www.geographystudio.org/productions', 'status': 'active'},
  {'name': 'Nikita Slavin', 'url': 'https://kontikimaps.com', 'status': 'active'},
  {'name': 'Norwood Viviano', 'url': 'https://www.norwoodviviano.com/', 'status': 'active'},
  {'name': 'Oana Candit', 'url': 'https://oanacanditmaps.ro/portfolio/', 'status': 'active'},
  {'name': 'Oliver Uberti', 'url': 'https://www.oliveruberti.com/', 'status': 'active'},
  {'name': 'Olivia Brotheridge', 'url': 'https://www.oliviadesign.uk/', 'status': 'active'},
  {'name': 'Owen Powell', 'url': 'https://owenpowell.wordpress.com/', 'status': 'active'},
  {'name': 'Paul J Pugliese', 'url': 'https://cartographybypaul.com/', 'status': 'inactive'},
  {'name': 'Perrin Remonté', 'url': 'https://www.perrinremonte.com/fraccueil-1', 'status': 'active'},
  {'name': 'Peter Atwood', 'url': 'https://peteratwoodprojects.wordpress.com/', 'status': 'active'},
  {'name': 'Phillip Pearson', 'url': 'https://shadedreliefmapping.myportfolio.com/work', 'status': 'active'},
  {'name': 'Phoebe Ly', 'url': 'https://phoebely.com/', 'status': 'active'},
  {'name': 'Raluca Nicola', 'url': 'https://raluca-nicola.net/', 'status': 'active'},
  {'name': 'Reynold Mackey', 'url': 'https://globesculptures.com/', 'status': 'active'},
  {'name': 'Riley D. Champine', 'url': 'https://www.rileydchampine.com/', 'status': 'active'},
  {'name': 'RJ Andrews', 'url': 'https://infowetrust.com/work', 'status': 'active'},
  {'name': 'Rosemary Wardley', 'url': 'https://rwardley.github.io/', 'status': 'active'},
  {'name': 'Roger Smith', 'url': 'https://www.geographx.co.nz/', 'status': 'active'},
  {'name': 'Sam Usle', 'url': 'https://www.studioredcar.com/urban-design', 'status': 'active'},
  {'name': 'Samuel Bucheli', 'url': 'https://samuelbucheli.myportfolio.com/projects', 'status': 'active'},
  {'name': 'Sara Drake', 'url': 'https://www.saradrake.com/', 'status': 'active'},
  {'name': 'Sarah Bell', 'url': 'https://www.sarahbellmaps.com/portfolio/', 'status': 'active'},
  {'name': 'Shane Loeffler', 'url': 'https://shaneloeffler.com/', 'status': 'active'},
  {'name': 'Shuoyan Huang', 'url': 'https://shuoyanhuang.github.io/#projects', 'status': 'active'},
  {'name': 'Simon Polster', 'url': 'https://cartisan.org/portfolio/1/', 'status': 'active'},
  {'name': 'Sophie Parr', 'url': 'https://mapsbysophie.com/', 'status': 'active'},
  {'name': 'Soren Walljasper', 'url': 'https://swalljasper.github.io/', 'status': 'active'},
  {'name': 'Spyridon Staridas', 'url': 'https://www.staridasgeography.gr/portfolio/', 'status': 'active'},
  {'name': 'Stephen Kennedy', 'url': 'https://workworkworkwork.work/', 'status': 'active'},
  {'name': 'Stephen Walter', 'url': 'https://stephenwalter.org/', 'status': 'active'},
  {'name': 'Stephen R. Smith', 'url': 'https://mapsmith.net/', 'status': 'active'},
  {'name': 'Sterling Quinn', 'url': 'https://sterlingquinn.net/recent-projects/', 'status': 'active'},
  {'name': 'Tania Willis', 'url': 'https://www.taniawillis.com/maps', 'status': 'active'},
  {'name': 'Tanner Arrington', 'url': 'https://freewheelmaps.com/', 'status': 'active'},
  {'name': 'Tibi Chelcea', 'url': 'https://tibichelcea.net/maps/', 'status': 'active'},
  {'name': 'Tiffany Chung', 'url': 'http://www.trfineart.com/artist/tiffany-chung/#artist-works', 'status': 'active'},
  {'name': 'Tim Wallace', 'url': 'https://timwallace.net/', 'status': 'active'},
  {'name': 'Tom Harrison', 'url': 'https://tomharrisonmaps.com/', 'status': 'active'},
  {'name': 'Tom Patterson', 'url': 'https://shadedrelief.com/map-gallery.html', 'status': 'active'},
  {'name': 'Topi Tjukanov', 'url': 'https://tjukanov.org/', 'status': 'active'},
  {'name': 'Travis Folk', 'url': 'https://newworldcartography.com/collections/all', 'status': 'active'},
  {'name': 'Travis White', 'url': 'https://visualvariables.com/projects/', 'status': 'inactive'},
  {'name': 'Vanessa Knoppke-Wetzel', 'url': 'https://vknoppkewetzel.github.io/', 'status': 'active'},
  {'name': 'Verena Klasen', 'url': 'https://verenaklasen.de/', 'status': 'active'},
  {'name': 'Vicky Johnson-Dahl', 'url': 'https://vickyjohnsondahl.com/', 'status': 'active'},
  {'name': 'Warren Davison Maps', 'url': 'https://warrenrdavison.wixsite.com/maps/projects', 'status': 'active'},
  {'name': 'Wes Jones', 'url': 'https://whatthejones.com/freelance-portfolio-work/', 'status': 'active'},
  {'name': 'Yuri Gordon', 'url': 'https://yurigordon.com/en/gallery/karty', 'status': 'active'},
  {'name': 'Zachary Ammerman', 'url': 'https://zammerman.myportfolio.com/work', 'status': 'active'},
];
